version: '3'

services:
  web:
    build:
      context: ./
    container_name: bingo
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.bingo.service=bingo"
      - "traefik.http.routers.bingo.rule=Host(`${TRAEFIK_PROXY_URL}`)"
      - "traefik.http.routers.bingo.entrypoints=websecure"
      - "traefik.http.routers.bingo.tls.certresolver=tlsresolver"
      - "traefik.http.services.bingo.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  public:
    external:
      name: ${TRAEFIK_PUBLIC_NETWORK}